//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report4Car.BENZReportServer {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BENZReportServer.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encrypt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string encrypt(string pinpai, string qihao, string yonghuming);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SearchUserRole(string userId, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchBigArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchBigArea(string userId, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSmallArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchSmallArea(string bigAreaCode, string userId, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchGroup(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchShop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchShop(string smallAreaCode, string userId, string groupCode, string projectCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchReportDownShop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchReportDownShop(string bigAreaCode, string smallAreaCode, string shopCode, string province, string city, string groupName, string carType, string projectCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Report4Car.BENZReportServer.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Report4Car.BENZReportServer.ServiceSoap>, Report4Car.BENZReportServer.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string encrypt(string pinpai, string qihao, string yonghuming) {
            return base.Channel.encrypt(pinpai, qihao, yonghuming);
        }
        
        public System.Data.DataSet SearchProject() {
            return base.Channel.SearchProject();
        }
        
        public string SearchUserRole(string userId, string projectCode) {
            return base.Channel.SearchUserRole(userId, projectCode);
        }
        
        public System.Data.DataSet SearchBigArea(string userId, string projectCode) {
            return base.Channel.SearchBigArea(userId, projectCode);
        }
        
        public System.Data.DataSet SearchSmallArea(string bigAreaCode, string userId, string projectCode) {
            return base.Channel.SearchSmallArea(bigAreaCode, userId, projectCode);
        }
        
        public System.Data.DataSet SearchGroup(string userId) {
            return base.Channel.SearchGroup(userId);
        }
        
        public System.Data.DataSet SearchShop(string smallAreaCode, string userId, string groupCode, string projectCode) {
            return base.Channel.SearchShop(smallAreaCode, userId, groupCode, projectCode);
        }
        
        public System.Data.DataSet SearchReportDownShop(string bigAreaCode, string smallAreaCode, string shopCode, string province, string city, string groupName, string carType, string projectCode) {
            return base.Channel.SearchReportDownShop(bigAreaCode, smallAreaCode, shopCode, province, city, groupName, carType, projectCode);
        }
    }
}
